### PR TITLE
Update to Build 20

### LINKED ISSUE #1: b20 is out
http://webcache.googleusercontent.com/search?q=cache:2ennphLOLbMJ:https://wl.widelands.org/news/2019/May/4/widelands-build-20-released/&hl=en&gl=pl&strip=1&vwsrc=0

### PR DESCRIPTION
**Pull request by scx**
Closes #1 

The bug preventing `Build 20` to build was fixed in the second half of July.
https://bugs.launchpad.net/widelands/+bug/1836107

See also:
https://github.com/scx/widelands-flatpak/commit/63b5cfef85254d4868a5a38d8466039e772d72f0

### CODE REVIEW

**Comment by scx** [comment]
You gotta be kidding me.
https://flathub.org/builds/#/builders/8/builds/753
```
flatpak run org.freedesktop.appstream-glib validate-strict builddir/*/share/appdata/org.widelands.Widelands.appdata.xml
 in dir /srv/buildbot/worker/build-x86_64-2/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run org.freedesktop.appstream-glib validate-strict builddir/*/share/appdata/org.widelands.Widelands.appdata.xml'
 using PTY: False
builddir/files/share/appdata/org.widelands.Widelands.appdata.xml: FAILED:
• attribute-invalid     : <screenshot> width too large [https://wl.widelands.org/wlmedia/wlscreens/screens/Build%2020/Four_Tribes_2.jpeg] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://wl.widelands.org/wlmedia/wlscreens/screens/Build%2020/Four_Tribes_2.jpeg] maximum is 900px
Validation of files failed
program finished with exit code 1
elapsedTime=2.724128
```
Discard the whole build just because one screenshot was "too big"?!

**Comment by scx** [comment]
Ah, no, it was an issue with Flathub infra. Even better...
```
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./flat-manager-client", line 678, in <module>
    "result": args.func(args),
  File "./flat-manager-client", line 476, in push_command
    upload_objects(args.repo_path, args.build_url, token, missing_file_objects)
  File "./flat-manager-client", line 223, in upload_objects
    upload_files(build_url, token, req)
  File "./flat-manager-client", line 197, in upload_files
    resp = session.request("post", build_url + '/upload', files=file_dict, headers={'Authorization': 'Bearer ' + token})
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
program finished with exit code 1
elapsedTime=641.574977
```

**Comment by scx** [comment]
bot, build org.widelands.Widelands

**Comment by scx** [comment]
bot, build org.widelands.Widelands

**Comment by stonerl** [comment]
Why did it fail this time?

**Comment by scx** [comment]
@stonerl 
> Why did it fail this time?

This is a Flathub infra problem. It builds fine, but it can't upload files (~200 MB).
It is random, so sometimes we have `arm` & `aarch64`, sometimes only `x86_64`, or `arm` & `aarch64` & `i386`.
I will try again later.

Anyway, I've provided a single-file bundle for x86_64, so if you want, you can test it:
https://github.com/scx/widelands-flatpak/releases

**Comment by stonerl** [comment]
@scx I tested your package on Mint and it works.

**Comment by scx** [comment]
bot, build org.widelands.Widelands

**Pull request merged**
