### PR TITLE
Update Widelands to github/master (feature freeze before release 1.0)

### PR DESCRIPTION
**Pull request by tothxa**
* Update Widelands to github/master (feature freeze before 1.0 release)
* Update freedesktop runtime to 20.08
* Update boost to 1.76
* Change version string handling once again...
* Remove dependencies: python2.7, xmlstarlet

### CODE REVIEW

**Comment by tothxa** [comment]
I'm sorry... I did build and test it, but then did this change which I thought would be just a cleanup.

**Comment by tothxa** [comment]
@barthalion Hello! Sorry for the @ but I'm not sure how this is supposed to be picked up. As far as I can tell @scx is the owner of this package, but he/she/? has not been active since August. Are flathub/flathub maintainers also notified of pull requests to existing packages? Can you approve it? If so, could you please check and approve if OK? Thanks!

**Comment by barthalion** [comment]
LGTM. @tothxa Would you be interested in getting write access to the repository?

**Comment by barthalion** [comment]
I think whatever makes sense from upstream's perspective. If fixes are in some branch despite the freeze, probably updating it to the latest commit/revision?

**Comment by barthalion** [comment]
I sent you an invite.

**Comment by tothxa** [comment]
> I sent you an invite.

Thank you once again.

**Pull request merged**
